/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e5e2e1",
        "surface-container-low": "#131313",
        "secondary-fixed-dim": "#d6d4d3",
        "on-secondary": "#525151",
        "on-surface": "#ffffff",
        "secondary": "#e5e2e1",
        "primary-dim": "#c7ef00",
        "on-primary-container": "#4c5d00",
        "on-tertiary-container": "#250400",
        "inverse-surface": "#fcf9f8",
        "primary-fixed": "#d1fc00",
        "surface-container": "#1a1a1a",
        "error-dim": "#d53d18",
        "outline": "#767575",
        "surface-bright": "#2c2c2c",
        "on-secondary-fixed": "#403f3f",
        "surface-dim": "#0e0e0e",
        "on-primary": "#546600",
        "on-primary-fixed": "#3c4a00",
        "outline-variant": "#484847",
        "tertiary-fixed": "#ff9475",
        "error-container": "#b92902",
        "on-primary-fixed-variant": "#556800",
        "surface-container-highest": "#262626",
        "surface-container-high": "#20201f",
        "on-tertiary-fixed-variant": "#6f1a00",
        "on-surface-variant": "#adaaaa",
        "background": "#0e0e0e",
        "on-tertiary": "#430c00",
        "surface-tint": "#f4ffc6",
        "tertiary-fixed-dim": "#ff7d57",
        "surface-variant": "#262626",
        "tertiary": "#ff734a",
        "on-error": "#450900",
        "primary-fixed-dim": "#c4ec00",
        "on-secondary-container": "#d2d0cf",
        "on-error-container": "#ffd2c8",
        "inverse-primary": "#546600",
        "on-tertiary-fixed": "#340800",
        "secondary-container": "#474746",
        "surface-container-lowest": "#000000",
        "tertiary-container": "#ff5722",
        "on-background": "#ffffff",
        "tertiary-dim": "#ff734a",
        "primary-container": "#d1fc00",
        "inverse-on-surface": "#565555",
        "primary": "#f4ffc6",
        "on-secondary-fixed-variant": "#5c5b5b",
        "secondary-dim": "#d6d4d3",
        "error": "#ff7351",
        "surface": "#0e0e0e"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
